### ISSUE TITLE
[Bug] 『南十字星恋歌』打包失败 + 『祝福の鐘の音は、桜色の風と共に』解包失败

### ISSUE THREAD

**Issue by natsumerinchan** [pkuislm/SAS5Tool#3]
作者你好，我在https://github.com/pkuislm/SAS5Tool/commit/9cce95e60830db0fdfcf29b8690f670b752b6af1 用vs2022编译后尝试解包这两款游戏的sec5，其中『南十字星恋歌』解包成功但打包失败，『祝福の鐘の音は、桜色の風と共に』直接无法解包

而我git reset --hard到https://github.com/pkuislm/SAS5Tool/commit/a4186178ba52d19e90903d4daf132072d0f0e03d 后『南十字星恋歌』可以正常打包，『祝福の鐘の音は、桜色の風と共に』则能解包，打包时仍然报和https://github.com/pkuislm/SAS5Tool/pull/2 一样的错，就算删掉menu.sal.txt打包后游戏也无法启动
![屏幕截图 2024-10-11 180751](https://github.com/user-attachments/assets/27494db3-d43e-4993-9acf-903827eb636f)

![屏幕截图 2024-10-11 180802](https://github.com/user-attachments/assets/8ac2bac0-ac0c-4064-bb6f-9b7b57b93cde)

附两者的sec5
[sec5.zip](https://github.com/user-attachments/files/17341466/sec5.zip)

**Comment by pkuislm** [comment]
南十字星恋歌打包错误是由于我先前push上github上的代码还是存在问题导致的，稍后我会再push一下。

关于祝福の鐘の音，它对应的引擎版本是109002。这个版本我并没有进行分析（毕竟我组也没有汉化所有绿茶社的游戏）。不过考虑到这个传奇程序员***秋山構平***写的代码，我觉得夏彩恋歌的110000应该是可以做到向后兼容的。我会在push前将这个版本暂时按照110000的支持情况写入代码，如果后续出现问题，请继续在此issue下反馈

**Comment by natsumerinchan** [comment]
问题已解决，十分感谢
